### ISSUE TITLE
sleep.ignore not for operator by default

### ISSUE THREAD

**Issue by derpierre65** [DailyStruggle/OnePlayerSleep#1]
please remove "sleep.ignore" permission from op by default

off topic: how can i remove the permission on my server for ops?

**Comment by DailyStruggle** [comment]
It would be awkward if a vanished operator triggered messages by accident. 

I'll change it from op to false, but I would generally recommend to set sleep.ignore to true for groups that don't want to announce themselves.

**Comment by DailyStruggle** [comment]
Server owners usually use a permission plugin (luckperms, pex, etc.) to create permission groups rather than using /op

You can set permission nodes to false to override default permissions

**Comment by DailyStruggle** [comment]
implemented in commit 4dab4a862cb6ef619ae0cce88297c686c9af3e2a
