### ISSUE TITLE
Unexplodable Beds In Nether?

### ISSUE THREAD

**Issue by Xarius86** [DailyStruggle/OnePlayerSleep#11]
Has anyone else experienced any issues with unexplodable beds in the nether? It is intermittent. Meaning, sometimes it will work, and other times it won't. This may or may not be due to OPS, I've been trying to track down the cause, but because it sometimes works and sometimes doesn't I haven't been able to figure it out. I've spent days on this. 

This last time it happened I was unable to explode a bed. So, I stopped the server, removed OPS, and started the server again. All the sudden, the bed was able to explode. So, I shut down the server, added OPS back, and then of course this time, it was still working again. Other times, I can do the same thing and it won't work after re-adding OPS. The same goes for other plugins as well. Sometimes it works, sometimes it doesn't. 

One avenue I've been looking into is if the time-of-day has something to do with it, and if it makes a difference when the TOD is different between the world, nether, and end. But, I haven't been able to come up with any reproducible routines. I *noticed* this issue only after updating Paper to 1.16.5, but no one over there seems to be having issues either, and again that just happened to be when I noticed it, not necessarily the cause of it.

So, this post is mostly just asking if anyone else has noticed anything weird with them.

**Comment by DailyStruggle** [comment]
I presume this also happens in the end.

I've seen similar bug reports for Minecraft. Does the bed disappear?

There are often methods to limit/delay explosions implemented in other plugins and in Minecraft. Other people can be a random factor. Does this happen when the TPS is low and/or other explosions are occurring?

This plugin doesn't do anything to bed events, aside from cooldown and timespan. https://github.com/DailyStruggle/OnePlayerSleep/blob/master/src/main/java/OnePlayerSleep/events/onPlayerBedEnter.java#L29

Does it give a cooldown message and work after waiting a few seconds?

**Comment by Xarius86** [comment]
I have not tested it in the end. 
The bed does not disappear; it just does nothing.
This occurs when I am the only person on the server, and the TPS is at a full 20. 
No other explosions would be occurring at the time.  
I do have GriefPrevention and IllegalStack running, but they are both set to allow explosions, fire, etc. outside of land claims. 
And no, waiting doesn't do anything either. The only console message that shows up is Essentials doing its routine check for sethome.
It's just really odd that it sometimes works and sometimes doesn't. I just can't seem to find the cause. 
I can place a bed and try to explode it and have it not work. I can leave the bed there, restart the server, then have a 50/50 chance of that exact same bed, in the exact same unmoved place either exploding or continuing to not work, seemingly at random.

And yeah, running through your code, it doesn't look like anything there would be interfering.

Thanks for your response, and if you do hear anything through the grapevine, please let me know :)

**Comment by DailyStruggle** [comment]
was able to reproduce the problem.

it seems there's an unexpected relationship between the time-based event cancellation and bed explosions. I had assumed the explosion happened before bed enter. 

I'll fix it and segment the code to make some config options to do/don't do sleep stuff in the nether/end and do/don't do explosions accordingly.

For now, setting the start and stop times to 0 and 23999 should fix the problem while still limiting the sleep times to default in the overworld.

**Comment by DailyStruggle** [comment]
fixed with 1.4.3

**Comment by Xarius86** [comment]
I'm glad you figured it out! Thanks for looking into this and providing a quick fix!
