### ISSUE TITLE
Update for 1.17

### ISSUE THREAD

**Issue by Xarius86** [DailyStruggle/OnePlayerSleep#13]
I know 1.17 introduced a new vanilla sleep mechanic that essentially allows one player to sleep, so I removed OPS when I did the upgrade to 1.17 last night. (Not because I didn't like the plugin, but I removed anything that wasn't essential that wasn't marked as 1.17 compatible.)

But -- it's not the same without your plugin. It doesn't have the messages, and especially doesn't have the ability to cancel skipping the night by other players. I haven't loaded the current OPS into my server, it very well could just work as is, or maybe it won't. I'd feel much more comfortable running it if you signed off on 1.17 compatibility being mostly stable. 

Thanks again for an excellent plugin - Mojang tried to do what you did, but you did it better.

**Comment by DailyStruggle** [comment]
3.0 update is in-progress.

For now, you can clone the repo and compile with java 16 if you want the current plugin in a 1.17 server.

**Comment by DailyStruggle** [comment]
Done.
