### ISSUE TITLE
"False" console spam

### ISSUE THREAD

**Issue by bugattiboy01** [DailyStruggle/OnePlayerSleep#14]
For months ive had console spam like

False
False
False
False
1

using a modified version of sysoutcatcher, Finally managed to catch the cause 

[00:21:30 INFO]: [OnePlayerSleep] false
[00:21:30 INFO]: [OnePlayerSleep] 1

Sometimes it spams False once per tick for many many rows in the console. 

Please fix xD

**Comment by DailyStruggle** [comment]
bug is outdated as of today's update
