### ISSUE TITLE
Weather not resetting after sleep

### ISSUE THREAD

**Issue by PatrickNorton** [DailyStruggle/OnePlayerSleep#18]
When sleeping through the night, weather is not cleared after waking up, unless the player sleeping is a server admin. Furthermore, sleeping during a thunderstorm does not stop it, but instead the player remains in the bed indefinitely until the storm stops (again, unless the player is an admin). The server is Paper 1.17.1.

**Comment by DailyStruggle** [comment]
Are you sure you aren't mixing weather plugins or have something that's messing with sleepingIgnored?

I'm not seeing any issues with weather or any differences between players and operators.

**Comment by DailyStruggle** [comment]
can't reproduce
