### ISSUE TITLE
sleep messages 

### ISSUE THREAD

**Issue by Lushanyamarie** [DailyStruggle/OnePlayerSleep#9]
one player sleep is working but none of messages are showing up in chat. nothing at all signifying anyone even slept.

**Comment by DailyStruggle** [comment]
is there more than one player active?

**Comment by DailyStruggle** [comment]
the plugin does not currently override the default sleep mechanic when there are fewer than 2 unignored players.

**Comment by DailyStruggle** [comment]
If there is a bug here, I am unable to replicate it on the latest version with the info available.
